version: "3"
services:
 mqtt:
      image: eclipse-mosquitto
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped  
 detection:
      image: detection
      build: .
      depends_on:
        - "mqtt"
      volumes:
        - /dev/video0:/dev/video0
      privileged: true
